home_spider/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homelink/', include('homelink.urls')),
]

homelink/urls.py
from django.urls import path
from . import views

app_name = 'homelink'

urlpatterns = [
    path('', views.search_data, name='search_data'),
    path('get_species_databases/', views.search_result, name='search_result'),
]

homelink/models.py
from django.db import models

# Create your models here.


class HouseInfo(models.Model):
    dbname = models.CharField(max_length=256, verbose_name='dbname',default='human')
    dbtype = models.CharField(max_length=20, verbose_name='dbtype',default='core')

    def __str__(self):
        return "{}-{}".format(self.dbname,self.dbtype)

    class Meta:
        verbose_name = "datbase"

homelink/forms.py
from django import forms



DBTYPE_CHOICES = (('core', 'core'), ('funcgen', 'funcgen'), ('otherfeatures', 'otherfeatures'),('rnaseq', 'rnaseq'),('variation','variation'),('cdna','cdna'),('vega','vega'))



class HouseChoiceForm(forms.Form):
    dbname = forms.CharField(label='Specie', max_length=50)
    release = forms.IntegerField(label='Release')
    dbtype = forms.CharField(label="Type", widget=forms.RadioSelect(choices=DBTYPE_CHOICES), required=False)

homelink/views.py
from django.shortcuts import render
from .forms import HouseChoiceForm
from django.http import HttpResponseRedirect
from fake_useragent import UserAgent
import requests
import mysql.connector



# Create your views here.

def search_data(request):
    form = HouseChoiceForm()
    return render(request, 'homelink/index.html', {'form': form, })


def search_result(request):
    if request.method == 'POST':
        form = HouseChoiceForm(request.POST)
        if form.is_valid():
            species = form.cleaned_data.get('dbname')
            dbtype = form.cleaned_data.get('dbtype')
            release = form.cleaned_data.get('release')
        data_list = data_query(species, dbtype, release)
        return render(request, 'homelink/results.html', {'my_list': data_list})
    else:
        return HttpResponseRedirect('/homelink/')   


def data_query(species, dbtype, release):    
    if species == 'human':
        species = 'homo_sapiens'    
    cnx = mysql.connector.connect(user='anonymous',host='ensembldb.ensembl.org',port='3306',database='ensembl_metadata_104')
    if dbtype == '':
        sql = "select dbname,type from genome_database where dbname LIKE" + " '"+ species + "%\_" + str(release) + "\_%'" + " ;" 
    else:
        sql = "select dbname,type from genome_database where dbname LIKE" + " '"+ species + "%\_" + str(release) + "\_%'" + " and type = " + "'"+str(dbtype)+"'" + " ;" 
    cursor = cnx.cursor()
    cursor.execute(sql)
    cresults = cursor.fetchall()
    data_list = []
    
    for i in cresults:
        data_list.append({'dbname':i[0],'type':i[1]})
    
    cnx.close()
    cursor.close()
    return data_list


    

homelink/templates/homelink/base.html
{% load static %}

<html lang="en">
<head>
<title>{% block title %}get_species_databases{% endblock %} </title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <style>
        ul li {
        display:inline;
        list-style-type:none;
        }
    </style>
</head>

<body>
 <!-- Page content of course! -->
<main>
    <div class="container">
    {% block content %}
  {% if error_message %}<p><strong>{{ error_message}}</strong></p>{% endif %}
  {% endblock %}
        </div>
</main>


<footer class="footer">
  {% block footer %}{% endblock %}
</footer>
<!--End of Footer-->

<!-- Bootstrap core JavaScript
================================================== -->

<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

homelink/templates/homelink/index.html
{% extends "homelink/base.html" %}

{% block content %}

<h3>Search_Ensembl</h3>
<form method="POST" class="form-horizontal" role='form' action="{% url 'homelink:search_result' %}">
  {% csrf_token %}
  {{ form.as_p }}
   <div class="form-group">
       <div class="col-md-12">
  <button type="submit" class="btn btn-primary form-control">SEARCH</button>
       </div>
   </div>
</form>

{% if page_obj %}
<h3>database information</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th>name</th>
			<th>type</th>
        </tr>
    </thead>
    <tbody>
     {% for house in page_obj %}
        <tr>
            <td>
            {{ house.dbname }}
            </td>
            <td>
            {{ house.dbtype }}
            </td>
     {% endfor %}
        </tr>
    </tbody>
</table>

{% else %}



{% endif %}



{% if is_paginated %}
     <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Previous</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
      <li class="page-item active"><span class="page-link"> {{ i }} <span class="sr-only">(current)</span></span></li>
       {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
       {% endif %}
    {% endfor %}

         {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% else %}
      <li class="page-item disabled"><span class="page-link">Next</span></li>
    {% endif %}
    </ul>

{% endif %}

{% endblock %}

homelink/templates/homelink/results.html
<!DOCTYPE html>
<html>
<head>
<title>get_species_databases_result</title>
</head>
<body>


<p>{{ my_list }}</p>



</body>
</html>

homelink/templates/homelink/search.html
{% extends "homelink/base.html" %}

{% block content %}

<h3>爬取上海链家二手房信息</h3>
<form method="POST" class="form-horizontal" role='form' action="{% url 'homelink:house_spider' %}">
  {% csrf_token %}
  {{ form.as_p }}
   <div class="form-group">
       <div class="col-md-12">
  <button type="submit" class="btn btn-primary form-control">开始爬取</button>
       </div>
   </div>
</form>


{% endblock %}